spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/safeguard_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.safeguard.entity,com.safeguard.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT Configuration
jwt:
  secret: "YourSuperSecretKeyForJWTTokenGenerationMustBe256BitsLong"
  expiration: 86400000

# File Upload
file:
  upload-dir: ./uploads

server:
  port: 8080

logging:
  level:
    root: INFO
    com.safeguard: DEBUG
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: backend-spring


